apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: squid
            - name: POSTGRES_PASSWORD
              value: WEDIOqwjdio9q2we312d328r243r
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 4350
      targetPort: 4350

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: trackersregistry.azurecr.io/manta-squid:3.0
          env:
            - name: DB_NAME
              value: squid
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: db
            - name: DB_PASS
              value: WEDIOqwjdio9q2we312d328r243r
            - name: GQL_PORT
              value: "4350"
          ports:
            - containerPort: 4350
          command: ["sqd", "serve:prod"]

---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 4350
    targetPort: 4350
  selector:
    app: api
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: processor
spec:
  selector:
    app: processor
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: trackersregistry.azurecr.io/manta-squid:3.0
          env:
            - name: DB_NAME
              value: squid
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: db
            - name: DB_PASS
              value: WEDIOqwjdio9q2we312d328r243r
          ports:
            - containerPort: 3000
          command: ["sqd", "process:prod"]